/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StockStatus = IDL.Variant({
  'Low' : IDL.Null,
  'OutOfStock' : IDL.Null,
  'InStock' : IDL.Null,
});
export const BikePart = IDL.Record({
  'id' : IDL.Text,
  'sellerPhone' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'distance' : IDL.Text,
  'sellerName' : IDL.Text,
  'stock' : StockStatus,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'sellerAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  'filterByBrand' : IDL.Func([IDL.Text], [IDL.Vec(BikePart)], ['query']),
  'filterByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BikePart)], ['query']),
  'getAllParts' : IDL.Func([], [IDL.Vec(BikePart)], ['query']),
  'getFilteredParts' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(BikePart)],
      ['query'],
    ),
  'getPartById' : IDL.Func([IDL.Text], [IDL.Opt(BikePart)], ['query']),
  'searchParts' : IDL.Func([IDL.Text], [IDL.Vec(BikePart)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StockStatus = IDL.Variant({
    'Low' : IDL.Null,
    'OutOfStock' : IDL.Null,
    'InStock' : IDL.Null,
  });
  const BikePart = IDL.Record({
    'id' : IDL.Text,
    'sellerPhone' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'distance' : IDL.Text,
    'sellerName' : IDL.Text,
    'stock' : StockStatus,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'sellerAddress' : IDL.Text,
  });
  
  return IDL.Service({
    'filterByBrand' : IDL.Func([IDL.Text], [IDL.Vec(BikePart)], ['query']),
    'filterByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BikePart)], ['query']),
    'getAllParts' : IDL.Func([], [IDL.Vec(BikePart)], ['query']),
    'getFilteredParts' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(BikePart)],
        ['query'],
      ),
    'getPartById' : IDL.Func([IDL.Text], [IDL.Opt(BikePart)], ['query']),
    'searchParts' : IDL.Func([IDL.Text], [IDL.Vec(BikePart)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };