/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BikePart {
  'id' : string,
  'sellerPhone' : string,
  'name' : string,
  'description' : string,
  'distance' : string,
  'sellerName' : string,
  'stock' : StockStatus,
  'imageUrl' : string,
  'category' : string,
  'brand' : string,
  'price' : bigint,
  'sellerAddress' : string,
}
export type StockStatus = { 'Low' : null } |
  { 'OutOfStock' : null } |
  { 'InStock' : null };
export interface _SERVICE {
  'filterByBrand' : ActorMethod<[string], Array<BikePart>>,
  'filterByCategory' : ActorMethod<[string], Array<BikePart>>,
  'getAllParts' : ActorMethod<[], Array<BikePart>>,
  'getFilteredParts' : ActorMethod<[string, string, string], Array<BikePart>>,
  'getPartById' : ActorMethod<[string], [] | [BikePart]>,
  'searchParts' : ActorMethod<[string], Array<BikePart>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];