/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BikePart {
    id: string;
    sellerPhone: string;
    name: string;
    description: string;
    distance: string;
    sellerName: string;
    stock: StockStatus;
    imageUrl: string;
    category: string;
    brand: string;
    price: bigint;
    sellerAddress: string;
}
export enum StockStatus {
    Low = "Low",
    OutOfStock = "OutOfStock",
    InStock = "InStock"
}
export interface backendInterface {
    filterByBrand(brand: string): Promise<Array<BikePart>>;
    filterByCategory(category: string): Promise<Array<BikePart>>;
    getAllParts(): Promise<Array<BikePart>>;
    getFilteredParts(q: string, brand: string, category: string): Promise<Array<BikePart>>;
    getPartById(id: string): Promise<BikePart | null>;
    searchParts(q: string): Promise<Array<BikePart>>;
}
import type { BikePart as _BikePart, StockStatus as _StockStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async filterByBrand(arg0: string): Promise<Array<BikePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByBrand(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByBrand(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterByCategory(arg0: string): Promise<Array<BikePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByCategory(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByCategory(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllParts(): Promise<Array<BikePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredParts(arg0: string, arg1: string, arg2: string): Promise<Array<BikePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredParts(arg0, arg1, arg2);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredParts(arg0, arg1, arg2);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartById(arg0: string): Promise<BikePart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchParts(arg0: string): Promise<Array<BikePart>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchParts(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchParts(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BikePart_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BikePart): BikePart {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_StockStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockStatus): StockStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BikePart]): BikePart | null {
    return value.length === 0 ? null : from_candid_BikePart_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    sellerPhone: string;
    name: string;
    description: string;
    distance: string;
    sellerName: string;
    stock: _StockStatus;
    imageUrl: string;
    category: string;
    brand: string;
    price: bigint;
    sellerAddress: string;
}): {
    id: string;
    sellerPhone: string;
    name: string;
    description: string;
    distance: string;
    sellerName: string;
    stock: StockStatus;
    imageUrl: string;
    category: string;
    brand: string;
    price: bigint;
    sellerAddress: string;
} {
    return {
        id: value.id,
        sellerPhone: value.sellerPhone,
        name: value.name,
        description: value.description,
        distance: value.distance,
        sellerName: value.sellerName,
        stock: from_candid_StockStatus_n4(_uploadFile, _downloadFile, value.stock),
        imageUrl: value.imageUrl,
        category: value.category,
        brand: value.brand,
        price: value.price,
        sellerAddress: value.sellerAddress
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    OutOfStock: null;
} | {
    InStock: null;
}): StockStatus {
    return "Low" in value ? StockStatus.Low : "OutOfStock" in value ? StockStatus.OutOfStock : "InStock" in value ? StockStatus.InStock : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BikePart>): Array<BikePart> {
    return value.map((x)=>from_candid_BikePart_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
